{{
    config(
        materialized='view',
        schema='EDP_RAW'
    )
}}
select 
    ID::VARCHAR(38) AS ID,
    EMPLOYEE_NAME::VARCHAR(30) AS EMPLOYEE_NAME,
    DATE_OF_BIRTH::TIMESTAMP_TZ(9) AS DATE_OF_BIRTH,
    ROW_STATUS_IND::VARCHAR(2) AS ROW_STATUS_IND,
    CLIENT_NAME::VARCHAR(15) AS CLIENT_NAME,
    CLIENT_REGION::VARCHAR(20) AS CLIENT_REGION,
    AUDIT_TIMESTAMP::TIMESTAMP_NTZ AS AUDIT_TIMESTAMP,
    SOURCE::VARCHAR(20) AS SOURCE
From {{ source('RAW', 'EPMS_EMPLOYEE') }}
WHERE ID IS NOT NULL