{{
    config(
        materialized='view',
        schema='EDP_RAW'
    )
}}
select 
    ID::VARCHAR(38) AS ID,
    DEPARTMENT_NAME::VARCHAR(30) AS DEPARTMENT_NAME,
    EMPLOYEE_ID::VARCHAR(10) AS EMPLOYEE_ID,
    DATE_OF_BIRTH::TIMESTAMP_TZ(9) AS DATE_OF_BIRTH,
    ROW_STATUS_IND::VARCHAR(2) AS ROW_STATUS_IND,
    CLIENT_NAME::VARCHAR(15) AS CLIENT_NAME,
    CLIENT_REGION::VARCHAR(20) AS CLIENT_REGION,
    AUDIT_TIMESTAMP::TIMESTAMP_NTZ AS AUDIT_TIMESTAMP,
    SOURCE::VARCHAR(20) AS SOURCE
From {{ source('RAW', 'EPMS_DEPARTMENT') }}
WHERE ID IS NOT NULL